# Generated by Django 3.2.18 on 2023-04-08 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prd_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='cust_id',
            field=models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
