# Generated by Django 3.2.18 on 2023-04-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ord_id',
            new_name='id',
        ),
    ]
