# Generated by Django 3.2.18 on 2023-04-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_ord_id_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='ord_id',
        ),
    ]
