# Generated by Django 3.2.18 on 2023-04-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_id_order_ord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ord_id',
            new_name='id',
        ),
    ]
