# Generated by Django 3.2.18 on 2023-09-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_ord_id_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '주문(orders)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '상품(product)'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '고객(customer)'},
        ),
    ]
