# Generated by Django 3.2.18 on 2023-09-11 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20230903_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order20',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders20)',
                'db_table': 'orders20',
            },
        ),
        migrations.CreateModel(
            name='Order19',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders19)',
                'db_table': 'orders19',
            },
        ),
        migrations.CreateModel(
            name='Order18',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders18)',
                'db_table': 'orders18',
            },
        ),
        migrations.CreateModel(
            name='Order17',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders17)',
                'db_table': 'orders17',
            },
        ),
        migrations.CreateModel(
            name='Order16',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders16)',
                'db_table': 'orders16',
            },
        ),
        migrations.CreateModel(
            name='Order15',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders15)',
                'db_table': 'orders15',
            },
        ),
        migrations.CreateModel(
            name='Order14',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders14)',
                'db_table': 'orders14',
            },
        ),
        migrations.CreateModel(
            name='Order13',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders13)',
                'db_table': 'orders13',
            },
        ),
        migrations.CreateModel(
            name='Order12',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders12)',
                'db_table': 'orders12',
            },
        ),
        migrations.CreateModel(
            name='Order11',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders11)',
                'db_table': 'orders11',
            },
        ),
        migrations.CreateModel(
            name='Order10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders10)',
                'db_table': 'orders10',
            },
        ),
        migrations.CreateModel(
            name='Order09',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders09)',
                'db_table': 'orders09',
            },
        ),
        migrations.CreateModel(
            name='Order08',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders08)',
                'db_table': 'orders08',
            },
        ),
        migrations.CreateModel(
            name='Order07',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders07)',
                'db_table': 'orders07',
            },
        ),
        migrations.CreateModel(
            name='Order06',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders06)',
                'db_table': 'orders06',
            },
        ),
        migrations.CreateModel(
            name='Order05',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders05)',
                'db_table': 'orders05',
            },
        ),
        migrations.CreateModel(
            name='Order04',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders04)',
                'db_table': 'orders04',
            },
        ),
        migrations.CreateModel(
            name='Order03',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders03)',
                'db_table': 'orders03',
            },
        ),
        migrations.CreateModel(
            name='Order02',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders02)',
                'db_table': 'orders02',
            },
        ),
        migrations.CreateModel(
            name='Order01',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_cnt', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_dt', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prd_id', models.ForeignKey(db_column='prd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
            options={
                'verbose_name_plural': '주문(orders01)',
                'db_table': 'orders01',
            },
        ),
    ]
